### ISSUE TITLE
JoinField is not showing anything for a relation

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2784]
I have a view of a table that has a one-to-one relationship with another table (the joining field resides in the latter). When I add a JoinField to this view in order to display a field of the latter table, I am presented with a relations dropdown where I can select said field. However, when running the view, nothing is shown. As a workaround, I instead createda show view of the field in question and embedded it, which worked, but since not every row of the parent view table
is linked in the other table, I get this clunky "No row selected" placeholder instead, which I can't seem to get rid of. Am I doing something wrong?

![image](https://github.com/user-attachments/assets/bd8a8ab1-36aa-4d12-b5ba-6a3eaf051d21)
![image](https://github.com/user-attachments/assets/da41a48c-8548-4731-8fb1-0984d2ce5321)

**Comment by iron3oxide** [comment]
@glutamate Indeed it is, I'll test if the behaviour is the same for a one-to-many relationship on the same table and report my findings.

**Comment by iron3oxide** [comment]
Making the key field non-unique lead to the same behaviour, however the "relations" dropdown wasn't present anymore in the configuration of the JoinField as seen in the screenshot below, so that's probably the reason for that.
![image](https://github.com/user-attachments/assets/028adfed-283d-460c-a82b-321cc33ad1c6)

**Comment by glutamate** [comment]
yeah i can replicate the error. I think it is quick to fix

**Comment by glutamate** [comment]
Fixed in #2785 . I assume that you @iron3oxide had either some upper case letters or spaces in one of the table names

**Comment by iron3oxide** [comment]
Yep, uppercase letters it was. Thanks for the quick fix!

**Comment by iron3oxide** [comment]
@glutamate I just upgraded to rc5, unfortunately the problem persists for me. Tested it with a stored calculated field and a "normal" field, both won't show anything

**Comment by glutamate** [comment]
sure, can you upload a pack here, or send some screenshots of your configuration

**Comment by iron3oxide** [comment]
Sure!
![image](https://github.com/user-attachments/assets/3198c3e9-20cd-4391-b46e-9d6c67ef70e1)
`bett` is a one-to-one relationship and there are definitely rows in the `Einträge` table that have one defined. The pictured view is used as the card view for a Kanban view. The icons are shown correctly in the Kanban view, the join fields remain empty (one can't see it here, but the icons are actually dynamic as they are each determined by a calculated string field that generates the appropriate fontawesome icon string which is then displayed in an as_html field).

**Comment by glutamate** [comment]
I can't replicate. On 1.1.0-beta.0:

I have Table A:

![image](https://github.com/user-attachments/assets/ca524ea6-fc0a-47aa-8f10-6f625912fd41)

Table B: 

![image](https://github.com/user-attachments/assets/5a6de282-8253-43b8-8b16-f2fcf05f1580)

Show on A: 

![image](https://github.com/user-attachments/assets/fe49a53b-e530-45d1-968a-da04600527ec)

Kanban on A:

![image](https://github.com/user-attachments/assets/fd1c20ab-f051-4d97-8bbd-83fe813b9b97)

gives result:

![image](https://github.com/user-attachments/assets/543f2cd7-ce34-487d-a650-46eb06461c2e)


Can you see any way in which this is different from your example?

**Comment by iron3oxide** [comment]
Truthfully I can't, other than that I included my FK in full text search and that I'm using UUIDs. Maybe it's best if I send you a zip via email again?

**Comment by glutamate** [comment]
Just tried with UUIDs and i still can't replicate, so yes maybe its best if you send me a backup

**Comment by glutamate** [comment]
Thanks for sending, i think there are also some problems with umlauts. Just tried ø in a table name and it messes everything up

**Comment by glutamate** [comment]
should be fixed in #2869

**Comment by glutamate** [comment]
@iron3oxide please check with 1.1.0-beta.10

**Comment by iron3oxide** [comment]
Can confirm it works now, thanks!
